###

GET http://localhost:3000/usuarios

###
GET http://localhost:3000/ordernarUsuarios?page=1&limit=5

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Deadpool",
    "senha": "123",
    "email": "pooly@gmail.com",
    "telefone": "48923256969"
}

###

DELETE http://localhost:3000/usuarios/
###

PUT http://localhost:3000/usuarios/11
Content-Type: application/json

{
    "nome": "Marcos",
    "senha": "123",
    "email": "marquin@gmail.com",
    "telefone": "48999216611",
    "ativo": false
}

###
GET http://localhost:3000/categorias

###

POST http://localhost:3000/categorias
Content-Type: application/json

{
    "nome": "Doce"
}

###

DELETE http://localhost:3000/categorias/

###

PUT http://localhost:3000/categorias/2
Content-Type: application/json

{
    "nome": "Lanche"
}


###

GET http://localhost:3000/receitas?page=1&limit=10

###

GET http://localhost:3000/receitas?page=1&limit=10&sort=nome&order=asc

###

POST http://localhost:3000/receitas
Content-Type: application/json 

{
    "nome": "Bolo de baunilha",
    "modo_preparo": "corta baunilha, mistura com trigo, leva ao forno",
    "ingredientes": "baunilha, trigo, ovo",
    "usuario_id": 18,
    "categoria_id": 3,
    "porcoes": 12,
    "tempo_preparo_minutos": 45
}