###
GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Renato",
    "senha": "123",
    "email": "renato@gmail.com",
    "telefone": "48999216613"
}

###
GET http://localhost:3000/categorias

###

POST http://localhost:3000/categorias
Content-Type: application/json

{
    "nome": "Doce"
}

###

DELETE http://localhost:3000/usuarios/

###

PUT http://localhost:3000/usuarios/11
Content-Type: application/json

{
    "nome": "Marcos",
    "senha": "123",
    "email": "marquin@gmail.com",
    "telefone": "48999216611"
}

###

DELETE http://localhost:3000/categorias/

###

PUT http://localhost:3000/categorias/2
Content-Type: application/json

{
    "nome": "Lanche"
}